// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAzmJ0U02r5JfALPHCZ13RdRZTEBoNjRo',
    appId: '1:5879085474:web:cec8a0ac054a5469509afb',
    messagingSenderId: '5879085474',
    projectId: 'inventurv2',
    authDomain: 'inventurv2.firebaseapp.com',
    storageBucket: 'inventurv2.appspot.com',
    measurementId: 'G-0F6N8J5CJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJVZzDQ8wrpVi64-TZk1QoD5MJarOaqiM',
    appId: '1:5879085474:android:6468c9c0b6838638509afb',
    messagingSenderId: '5879085474',
    projectId: 'inventurv2',
    storageBucket: 'inventurv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJL6NS-aNl-D17iiMFmmKQCcV8qO693cA',
    appId: '1:5879085474:ios:c9b396a8454e8d72509afb',
    messagingSenderId: '5879085474',
    projectId: 'inventurv2',
    storageBucket: 'inventurv2.appspot.com',
    iosBundleId: 'com.example.inventurV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJL6NS-aNl-D17iiMFmmKQCcV8qO693cA',
    appId: '1:5879085474:ios:e71486dbffdde4b1509afb',
    messagingSenderId: '5879085474',
    projectId: 'inventurv2',
    storageBucket: 'inventurv2.appspot.com',
    iosBundleId: 'com.example.inventurV2.RunnerTests',
  );
}
